/**
 * Individual à la carte services for RV park owners — no bundled tiers,
 * no packages. Park owners pick what they need. All fixed prices in cents
 * (Stripe convention). Keep this in sync with api/create-checkout-session.js —
 * the serverless function duplicates these entries since it runs in a
 * separate Node runtime and can't import this browser-side module directly.
 */

export const SERVICES = [
  {
    key: 'website-design',
    name: 'Website Design',
    icon: 'globe',
    setup: 185000,
    startingAt: true,
    desc: [
      'A modern, mobile-friendly website built specifically for your RV park',
      'AI chatbot, reservation system connection, and SEO optimization included',
      'Google Maps and Google Business Profile setup',
      'Contact forms and analytics setup',
    ],
  },
  {
    key: 'social-media',
    name: 'Social Media Management',
    icon: 'share',
    monthly: 49700,
    desc: [
      'Daily posts across Facebook and Instagram — photos, videos, and written content created by AI',
      'Seasonal promotions, park updates, and blog content',
      'Consistent brand presence without lifting a finger',
    ],
  },
  {
    key: 'ai-guest-finder',
    name: 'AI Guest Finder',
    icon: 'target',
    monthly: 99700,
    desc: [
      'AI finds travelers actively planning RV trips across Facebook, Instagram, Reddit, and travel platforms',
      'Reaches them before they book somewhere else',
      'Fills shoulder-season gaps that used to sit empty',
    ],
  },
  {
    key: 'ai-booking',
    name: 'AI Booking System',
    icon: 'calendar',
    monthly: 29700,
    desc: [
      'Follows up instantly and answers questions 24/7',
      'Books stays automatically without you touching a calendar',
      'Never lets a lead go cold overnight',
    ],
  },
  {
    key: 'ai-content',
    name: 'AI Content Creation',
    icon: 'camera',
    monthly: 47000,
    desc: [
      'Photos, videos, and written content generated by AI',
      'Keeps your site and socials fresh without a photographer on retainer',
      'On-brand, on-theme, ready to publish',
    ],
  },
  {
    key: 'review-reputation',
    name: 'Review and Reputation Marketing',
    icon: 'star',
    monthly: 19700,
    desc: [
      'Automatically requests 5-star reviews from happy guests',
      'Monitors and manages your online reputation',
      'Turns great stays into public proof',
    ],
  },
  {
    key: 'monthly-reporting',
    name: 'Monthly Reporting',
    icon: 'chart',
    monthly: 9700,
    desc: [
      'A plain-English monthly report on travelers reached, bookings, and occupancy trend',
      'Know exactly what\'s working — no guesswork',
    ],
  },
  {
    key: 'voice-ai',
    name: 'Voice AI Receptionist',
    icon: 'phone',
    setup: 100000,
    monthly: 45000,
    desc: [
      'Answers every call 24/7',
      'Books reservations automatically',
      'Never misses a call again',
    ],
  },
  {
    key: 'conversational-ai',
    name: 'Conversational AI on Email, SMS and DMs',
    icon: 'chat',
    setup: 70000,
    monthly: 30000,
    desc: [
      'AI handles replies and messages across Email, SMS, Instagram DM & Facebook DM',
      'Qualifies guests and books stays automatically',
      'Every channel covered, all day, every day',
    ],
  },
];

export function formatUsd(cents, { decimals = 0 } = {}) {
  return '$' + (cents / 100).toLocaleString('en-US', { minimumFractionDigits: decimals, maximumFractionDigits: decimals });
}
