/**
 * Individual à la carte services for RV park owners — no bundled tiers,
 * no packages. Park owners pick what they need. All fixed prices in cents
 * (Stripe convention). Keep this in sync with api/create-checkout-session.js —
 * the serverless function duplicates these entries since it runs in a
 * separate Node runtime and can't import this browser-side module directly.
 *
 * `shortDesc` is the one-line summary used on the homepage overview cards;
 * `desc` is the fuller bullet list used on the Services & Pricing page.
 */

export const SERVICES = [
  {
    key: 'website-design',
    name: 'Website Design',
    icon: 'globe',
    setup: 185000,
    startingAt: true,
    shortDesc: 'A modern, mobile-friendly site built to convert lookers into bookers.',
    desc: [
      'A modern, mobile-friendly website built specifically for your RV park',
      'AI chatbot, reservation system connection, and SEO optimization included',
      'Google Maps and Google Business Profile setup',
      'Contact forms and analytics setup',
    ],
  },
  {
    key: 'ai-guest-finder',
    name: 'AI Guest Finder',
    icon: 'target',
    monthly: 99700,
    shortDesc: 'AI finds travelers planning RV trips before they book somewhere else.',
    desc: [
      'AI finds travelers actively planning RV trips across Facebook, Instagram, Reddit, and travel platforms',
      'Reaches them before they book somewhere else',
      'Fills shoulder-season gaps that used to sit empty',
    ],
  },
  {
    key: 'ai-booking',
    name: 'AI Booking System',
    icon: 'calendar',
    monthly: 29700,
    shortDesc: 'Follows up instantly and books stays automatically, 24/7.',
    desc: [
      'Follows up instantly and answers questions 24/7',
      'Books stays automatically without you touching a calendar',
      'Never lets a lead go cold overnight',
    ],
  },
  {
    key: 'social-media',
    name: 'Social Media Management',
    icon: 'share',
    monthly: 49700,
    shortDesc: 'Daily AI-created posts keep your park active on Facebook and Instagram.',
    desc: [
      'Daily posts across Facebook and Instagram — photos, videos, and written content created by AI',
      'Seasonal promotions, park updates, and blog content',
      'Consistent brand presence without lifting a finger',
    ],
  },
  {
    key: 'ai-content',
    name: 'AI Content Creation',
    icon: 'camera',
    monthly: 47000,
    shortDesc: 'Fresh photos, video, and copy for your site and socials — no photographer needed.',
    desc: [
      'Photos, videos, and written content generated by AI',
      'Keeps your site and socials fresh without a photographer on retainer',
      'On-brand, on-theme, ready to publish',
    ],
  },
  {
    key: 'review-reputation',
    name: 'Review and Reputation Marketing',
    icon: 'star',
    monthly: 19700,
    shortDesc: 'Automatically turns happy guests into 5-star reviews.',
    desc: [
      'Automatically requests 5-star reviews from happy guests',
      'Monitors and manages your online reputation',
      'Turns great stays into public proof',
    ],
  },
  {
    key: 'financial-records',
    name: 'Financial Records & Revenue Tracking',
    icon: 'file-text',
    monthly: 14700,
    shortDesc: 'Clean monthly financial records — ready for your broker when you sell.',
    desc: [
      'Monthly revenue pulled from your booking system',
      'Occupancy rate tracking month by month',
      'Basic expense tracking and categorization',
      'Clean financial summary report every month',
      'Ready to hand directly to your broker when selling',
    ],
    disclaimer: 'RVParkSuccess.com is not an accounting firm. Any data gathered for the owner is only for evaluation purposes.',
  },
  {
    key: 'monthly-reporting',
    name: 'Monthly Reporting',
    icon: 'chart',
    monthly: 9700,
    shortDesc: 'A plain-English report on what\'s working, every month.',
    desc: [
      'A plain-English monthly report on travelers reached, bookings, and occupancy trend',
      'Know exactly what\'s working — no guesswork',
    ],
  },
  {
    key: 'voice-ai',
    name: 'Voice AI Receptionist',
    icon: 'phone',
    setup: 100000,
    monthly: 45000,
    shortDesc: 'Answers every call 24/7 and books reservations automatically.',
    desc: [
      'Answers every call 24/7',
      'Books reservations automatically',
      'Never misses a call again',
    ],
  },
  {
    key: 'conversational-ai',
    name: 'Conversational AI on Email, SMS and DMs',
    icon: 'chat',
    setup: 70000,
    monthly: 30000,
    shortDesc: 'AI handles Email, SMS, and DM replies — every channel, all day.',
    desc: [
      'AI handles replies and messages across Email, SMS, Instagram DM & Facebook DM',
      'Qualifies guests and books stays automatically',
      'Every channel covered, all day, every day',
    ],
  },
];

export function formatUsd(cents, { decimals = 0 } = {}) {
  return '$' + (cents / 100).toLocaleString('en-US', { minimumFractionDigits: decimals, maximumFractionDigits: decimals });
}
